service:
  name: youngblood-token-rewards

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-alexa-skills
provider:
  name: aws
  runtime: nodejs6.10
  environment:
      DYNAMODB_TABLE_TOKEN: Tokens-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:*"

functions:
  hello:
    handler: src/typescript/handler.hello
    events:
      - http:
          method: get
          path: hello
  createToken:
    handler: src/typescript/database/createToken.create
    events:
      - http:
          path: token
          method: post
          cors: true


resources:
  Resources:
    TokenTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain # Keeps around the DynamoDB resource when we redeploy/destroy
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE_TOKEN}

custom:
  alexa:
    vendorId: M1B7YGHR414YSA
    clientId: amzn1.application-oa2-client.28864766149d4e1f93689a0805738fcd
    clientSecret: 6402f77cf0c6fceee4214c57e831bdb48bd8e8c92a0bbe82f9a12e987401fa56