service:
  name: youngblood-token-rewards

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
    
provider:
  name: aws
  runtime: nodejs6.10
  environment:
      DYNAMODB_TABLE_TOKEN: Tokens-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:*"

functions:
  alexaToken:
    handler: src/typescript/alexaSkill/alexaToken.invokeTokenRewards
    events:
      - alexaSkill
  token:
    handler: src/typescript/rest/handler.invokeTokenRewards
    events:
      - http:
          method: get
          path: tokenrewards

resources:
  Resources:
    TokenTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain # Keeps around the DynamoDB resource when we redeploy/destroy
      Properties:
        AttributeDefinitions:
          -
            AttributeName: childName
            AttributeType: S
        KeySchema:
          -
            AttributeName: childName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE_TOKEN}
